In [1]:
import pandas as pd
import numpy as np

base_path = r"C:\Users\T10002\Downloads\supply_chain_management\data\processed"

supplier_master_df = pd.read_csv(
    base_path + r"\supplier_master.csv"
)

supplier_component_df = pd.read_csv(
    base_path + r"\supplier_component.csv"
)

purchase_orders_df = pd.read_csv(
    base_path + r"\purchase_orders.csv"
)

print("Supplier Master:")
print(supplier_master_df.shape)
display(supplier_master_df.head())

print("\nSupplier Component:")
print(supplier_component_df.shape)
display(supplier_component_df.head())

print("\nPurchase Orders:")
print(purchase_orders_df.shape)
display(purchase_orders_df.head())

Supplier Master:
(27, 10)

,supplier_id,supplier_name,location,component_category,lead_time_days,unit_cost,monthly_capacity,quality_rating,reliability_score,status
0,S001,Battery Systems India,Tamil Nadu,Battery,15,85000,12000,4.5,92,Active
1,S002,Advanced Energy Systems,Karnataka,Battery,18,88000,10000,4.3,89,Active
2,S003,EV Cell Technologies,Gujarat,Battery,25,4200,500000,4.2,87,Active
3,S004,PowerCell Manufacturing,Maharashtra,Battery,22,4500,450000,4.4,91,Active
4,S005,Electric Drive Systems,Tamil Nadu,Powertrain,20,42000,8000,4.4,94,Active

Supplier Component:
(91, 6)

,supplier_id,part_id,unit_cost,lead_time_days,minimum_order_quantity,monthly_capacity
0,S001,P001,85000,15,100,12000
1,S002,P001,88000,18,100,10000
2,S003,P002,4200,25,500,500000
3,S004,P002,4500,22,500,450000
4,S001,P003,3200,15,100,15000

Purchase Orders:
(2000, 14)

,po_id,po_date,supplier_id,part_id,warehouse,quantity_ordered,quantity_received,unit_cost,expected_delivery_date,actual_delivery_date,order_status,quantity_shortage,delivery_delay_days,order_value
0,PO00001,2025-12-10,S011,P021,Coimbatore,1252,1252,18000.0,2025-12-22,2025-12-22,Delivered,0,0,22536000.0
1,PO00002,2026-05-12,S011,P023,Chennai,541,378,3500.0,2026-05-24,2026-06-02,Late + Partial,163,9,1893500.0
2,PO00003,2025-06-10,S002,P005,Chengalpattu,1703,1703,16500.0,2025-06-29,2025-07-01,Delivered,0,2,28099500.0
3,PO00004,2025-04-02,S015,P029,Chennai,1477,1477,280.0,2025-04-20,2025-04-20,Delivered,0,0,413560.0
4,PO00005,2025-11-21,S005,P012,Hosur,615,615,14000.0,2025-12-09,2025-12-18,Late,0,9,8610000.0